name: Build and Push Docker Image to GHCR
description: Builds a Docker image and either pushes to GHCR or uploads a tarball artifact

inputs:
  artifact-name:
    required: false
    description: ''
  artifact-path:
    description: ''
    default: .
  platforms:
    description: ''
    default: linux/amd64,linux/arm64
  build-args:
    required: false
    description: ''
  context:
    description: ''
    default: .
  tag:
    required: false
    description: ''
  push:
    description: ''
    default: 'false'
  prune:
    description: ''
    default: 'true'
  debug:
    description: ''
    default: 'false'

runs:
  using: composite
  steps:
    - name: Get short commit hash
      id: git_commit
      run: echo "short_hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Image tag(s)
      id: image_tags
      run: |
        IFS=',' read -ra image_tags <<< "${{ inputs.tag || steps.git_commit.outputs.short_hash }}"
        first_tag="${image_tags[0]}"
        echo "tag_for_export=$first_tag" >> "$GITHUB_OUTPUT"
        output=""
        for image_tag in "${image_tags[@]}"; do
          trimmed_image_tag=$(echo "$image_tag" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          output+="ghcr.io/${{ github.repository }}:$trimmed_image_tag,"
        done
        output=$(echo "$output" | sed 's/,$//')
        echo "tags_for_registry=$output" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Check our image tags
      if: ${{ inputs.debug == 'true' }}
      run: |
        echo "tags_for_registry: ${{ steps.image_tags.outputs.tags_for_registry }}"
        echo "tag_for_export: ${{ steps.image_tags.outputs.tag_for_export }}"
      shell: bash
    
    - name: Download artifacts
      if: ${{ inputs.artifact-name != '' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    - name: See which artifacts we just downloaded
      if: ${{ inputs.artifact-name != '' && inputs.debug == 'true' }}
      run: ls ${{ inputs.artifact-path }} -lha
      shell: bash

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }} # The name of the person or app that initiated the workflow. For example, octocat.
        password: ${{ env.GITHUB_TOKEN }} # automatically provided by GitHub Actions, so you don't need to create it manually.

    - name: Build and push Docker image
      if: ${{ inputs.push == 'true' }}
      uses: docker/build-push-action@v4
      with:
        platforms: ${{ inputs.platforms }}
        build-args: ${{ inputs.build-args }}
        context: ${{ inputs.context }}
        push: true
        # GITHUB_REPOSITORY = The owner and repository name. For example, octocat/Hello-World.
        # ghcr.io prefix makes sure we are pushing to GHCR
        tags: ${{ steps.image_tags.outputs.tags_for_registry }} # octocat/Hello-World:ffac537

    - name: Build and export Docker image
      if: ${{ inputs.push != 'true' }}
      uses: docker/build-push-action@v4
      with:
        build-args: ${{ inputs.build-args }}
        context: ${{ inputs.context }}
        tags: ${{ github.repository }}:${{ steps.image_tags.outputs.tag_for_export }}
        outputs: type=docker,dest=/tmp/${{ github.event.repository.name }}.tar

    - name: Upload image artifacts
      if: ${{ inputs.push != 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.image_tags.outputs.tag_for_export }}
        path: /tmp/${{ github.event.repository.name }}.tar

    - name: Post cleanup
      if: ${{ inputs.prune == 'true' }}
      run: docker image prune -f
      shell: bash
