###
# This config is specifically for the MeshAdv Pi Hat from FrequencyLabs
# https://www.etsy.com/listing/1849074257/meshadv-pi-hat-v11-fully-assembled-1
# https://github.com/chrismyers2000/MeshAdv-Pi-Hat
###
---
Lora:
  # Choose only one module at a time
  Module: sx1262 # Ebyte E22-900M30S and E22-900M33S
  # Module: sx1268  # Ebyte E22 400M30S and E22-400M33S
  CS: 21
  IRQ: 16
  Busy: 20
  Reset: 18
  TXen: 13 # TX and RX enable pins
  RXen: 12
  DIO3_TCXO_VOLTAGE: true

### Set gpio chip to use in /dev/. Defaults to 0.
### Notably the Raspberry Pi 5 puts the GPIO header on gpiochip4
#  gpiochip: 4

### Specify the SPI device to use in /dev/. Defaults to spidev0.0
### Some devices, like the pinedio, may require spidev0.1 as a workaround.
#  spidev: spidev0.0

### Define GPIO buttons here:

GPIO:
#  User: 6

### Define GPS

GPS:
#  SerialPath: /dev/ttyS0

### Specify I2C device, or leave blank for none

I2C:
  I2CDevice: /dev/i2c-1

### Set up SPI displays here. Note that I2C displays are generally auto-detected.

Display:

### Waveshare 1.44inch LCD HAT
#  Panel: ST7735S
#  CS: 8         #Chip Select
#  DC: 25        # Data/Command pin
#  Backlight: 24
#  Width: 128
#  Height: 128
#  Reset: 27
#  OffsetX: 0
#  OffsetY: 0

### Adafruit PiTFT 2.8 TFT+Touchscreen
#  Panel: ILI9341
#  CS: 8
#  DC: 25
#  Width: 240
#  Height: 320
#  Rotate: true

### SHCHV 3.5 RPi TFT+Touchscreen
#  Panel: ILI9486
#  spidev: spidev0.0
#  BusFrequency: 30000000
#  DC: 24
#  Reset: 25
#  Width: 320
#  Height: 480
#  OffsetRotate: 2

### TZT 2.0 Inch TFT Display ST7789V 240RGBx320
#  Panel: ST7789
#  spidev: spidev0.0
#  # CS: 8     # can be freely chosen
#  BusFrequency: 80000000
#  DC: 24      # can be freely chosen
#  Width: 320
#  Height: 240
#  Reset: 25   # can be freely chosen
#  Rotate: true
#  OffsetRotate: 1
#  Invert: true

### You can also specify the spi device for the display to use
# spidev: spidev0.0

Touchscreen:
### Note, at least for now, the touchscreen must have a CS pin defined, even if you let Linux manage the CS switching.

#  Module: STMPE610 # Option 1 for Adafruit PiTFT 2.8
#  CS: 7
#  IRQ: 24

#  Module: FT5x06 # Option 2 for Adafruit PiTFT 2.8
#  IRQ: 24
#  I2CAddr: 0x38

### You can also specify the spi device for the touchscreen to use
# spidev: spidev0.0

Input:
### Configure device for direct keyboard input

#  KeyboardDevice: /dev/input/by-id/usb-_Raspberry_Pi_Internal_Keyboard-event-kbd

###

Logging:
  LogLevel: info # debug, info, warn, error
#  TraceFile: /var/log/meshtasticd.json
#  AsciiLogs: true     # default if not specified is !isatty() on stdout

Webserver:
#  Port: 443 # Port for Webserver & Webservices
#  RootPath: /usr/share/doc/meshtasticd/web # Root Dir of WebServer

General:
  MaxNodes: 200
  MaxMessageQueue: 100
  ConfigDirectory: /etc/meshtasticd/config.d/
