name: Run Shared Build and Push Workflow for lpic-labs

on:
  push:
    branches:
      - main
      - master
    paths:
      - "lpic-labs/Dockerfile"
      - "lpic-labs/*.sh"
  workflow_dispatch:

jobs:
  build_and_push_to_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: See which repo we just cloned
        if: ${{ vars.pipeline_debug == 'true' }}
        run: ls -alh
        shell: bash

      - name: Build and push to DockerHub
        uses: jabez007/docker-kitchen/.github/shared/docker@master
        with:
          context: ./lpic-labs
          image-name: ${{ vars.DOCKER_USERNAME }}/lpic-labs
          description: A Docker image alternative to VMs for LPIC-1 practice
          tag: latest
          push: true
          debug: ${{ vars.pipeline_debug }}
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

  build_and_push_to_ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # required if push is true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: See which repo we just cloned
        if: ${{ vars.pipeline_debug == 'true' }}
        run: ls -alh
        shell: bash

      - name: Build and push to GHCR
        uses: jabez007/docker-kitchen/.github/shared/ghcr@master
        with:
          context: ./lpic-labs
          image-name: jabez007/lpic-labs
          description: A Docker image alternative to VMs for LPIC-1 practice
          tag: latest
          push: true
          debug: ${{ vars.pipeline_debug }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
