name: Run Shared Build Workflow for aws-kubectl

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - "aws-kubectl/Dockerfile"
      - "aws-kubectl/*.sh"
      - "aws-kubectl/*.pem"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: foobar
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: See which repo we just cloned
        if: ${{ vars.pipeline_debug == 'true' }}
        run: ls -alh
        shell: bash

      - uses: jabez007/docker-kitchen/.github/shared/ghcr@master
        with:
          context: ./aws-kubectl
          image-name: jabez007/aws-kubectl
          tag: ${{ vars.AWS_REGION }}_${{ vars.EKS_CLUSTER }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            AWS_REGION=${{ vars.AWS_REGION }}
            EKS_CLUSTER=${{ vars.EKS_CLUSTER }}
          debug: ${{ vars.pipeline_debug }}
