name: Test Shared Scripts

on:
  push:

jobs:
  test_delimited-string:
    runs-on: ubuntu-latest
    steps:
      - name: Test delimited-string for Docker tags
        id: docker-tags
        uses: jabez007/docker-kitchen/.github/shared/script/delimited-string@master
        with:
          source_string: ", dev , tst , prd"
          target_delimiter: ", ghcr.io/foo-bar:"
          debug: true

      - name: Check delimited-string for Docker tags
        run: |
          expected=", ghcr.io/foo-bar:dev, ghcr.io/foo-bar:tst, ghcr.io/foo-bar:prd"
          if [ "${{ steps.docker-tags.outputs.target_string }}" != "$expected" ]; then
            echo "${{ steps.docker-tags.outputs.target_string }} does not match $expected"
            exit 1
          fi
